### ISSUE TITLE
Does it work on M1 Big Sur?

### ISSUE THREAD

**Issue by Peebuddy43** [godly-devotion/charge-limiter#12]
Somone managed to run it on a M1 MBP with Big Sur?

**Comment by godly-devotion** [comment]
Although I don't have a Mac with M1, I doubt this will work. Apple's support article regarding resetting the SMC says that the steps only apply to Mac computers with an Intel processor only. So its quite possible that Macs with M1 don't have SMC.

Reference: https://support.apple.com/en-us/HT201295

**Comment by Peebuddy43** [comment]
Thanks for the reply. So no chance of charge limiter work on m1? This feature was so awesome and should be a setting in OS. So sad :(
