### ISSUE TITLE
Mac won't let me download 

### ISSUE THREAD

**Issue by somrads** [godly-devotion/charge-limiter#13]
Probably because of the Big Sur update

**Comment by somrads** [comment]
nvm i got it

**Comment by godly-devotion** [comment]
Do you mind explaining what happened and how you fixed it? Maybe it can help others who have the same problem.

**Comment by somrads** [comment]
when I downloaded it my mac didn't let me open it because "it couldn't check for malicious malware" so i went to my system preferences to security & privacy en clicked on "open anyway". I forgot you have to do that when you download software from unidentified developers.

**Comment by godly-devotion** [comment]
Good point. I will add that to the README. Thanks!

**Comment by somrads** [comment]
No problem and thanks for making the charge limiter, it's a big help
