### ISSUE TITLE
Error with priviledges or M1 chip

### ISSUE THREAD

**Issue by luboxing** [godly-devotion/charge-limiter#14]
Thanks for the app! It is exactly what I am looking for.

I am running it on macOS Big Sur with M1 CPU. The error message after entering admin password is: "There was a problem setting the charge limit. Please make sure you have administrator priviledge". It might be due to the M1 chip or priviledge ... I am not sure...

**Comment by godly-devotion** [comment]
Apple's support article regarding resetting the SMC says that the steps only apply to Mac computers with an Intel processor only. So its quite possible that Macs with M1 don't have SMC at all. Unfortunately I don’t have a M1 Mac to do further testing so I don’t think support will come on the near future.

Reference: https://support.apple.com/en-us/HT201295
