### ISSUE TITLE
Working on Late 2013 MacBook Pro 

### ISSUE THREAD

**Issue by dannytang** [godly-devotion/charge-limiter#2]
I just wanted to say thanks! I have it running on my Late 2013 15" MacBook Pro. I set it to 77% and plugged in my MacBook Pro which was discharged to 38%. The MacBook Pro charged to 80% and then stopped, so far so good! Thanks again!

**Comment by godly-devotion** [comment]
Awesome! Good to hear that it works.

Just FYI, I made a sneaky release with the same version number to address a small bug (you can see it in the other issue ticket) so if you had trouble opening the app before, the latest release version as of this comment will fix that.
