### ISSUE TITLE
Charging percentages off

### ISSUE THREAD

**Issue by Dantasstic** [godly-devotion/charge-limiter#23]
If I want to charge to 80% I need to instead set the limiter to 77%, otherwise it will go over 80. 

It appears each charge % level requires guessing and trial and error to find out what to actually set the limiter to to hit the wanted target charge.

**Comment by godly-devotion** [comment]
What's happening is that macOS does not display the exact battery level on the status menu indicator. It is usually +2/3% higher than what it truly is. You can check by using a different battery monitoring app such as coconutBattery, which will show you that the percentage you set is where it actually stops charging.
