### ISSUE TITLE
Getting an error when I run: Error 1004: An error occurred.

### ISSUE THREAD

**Issue by NickStrupat** [godly-devotion/charge-limiter#30]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/782521/139959630-f3efb345-821f-4a27-b1cd-0fe7807130e8.png">

It was working for a few months before today. Hoping someone here knows how to fix this issue.

**Comment by godly-devotion** [comment]
What is your MacBook and macOS version? What was the last version that worked for you?

**Comment by NickStrupat** [comment]
MacBook is late 2013 (MacBookPro11,3)
macOS version is 10.15.7 (19H1217)

I believe the last version to work for me was 1.4.

The error happened after I updated today to 1.4.1, but I'm not sure exactly if that was the cause.

I installed 1.4 again and I still get the error.

**Comment by jenyunhuang** [comment]
I have same issues
macbook pro 2015 15" catalina 10.15.7

**Comment by NickStrupat** [comment]
I wonder if it's a `zsh` issue. When I run `sudo /Applications/Charge\ Limiter.app/Contents/Resources/smcutil -r BCLM` I get `illegal hardware instruction` followed by the command text.

**Comment by godly-devotion** [comment]
Could you please try this test build to see if it works? @MikeMaxNow If you don't mind, could you test this build to see if it works for you as well?

[Charge Limiter.zip](https://github.com/godly-devotion/charge-limiter/files/7464612/Charge.Limiter.zip)

**Comment by jenyunhuang** [comment]
The new file work for me

**Comment by NickStrupat** [comment]
Works for me too.

I did some thinking and realized it's probably that the embedded `smcutil` was compiled on a newer Mac with some instruction set extensions that aren't on my 2013 CPU. When my machine tries to run the instructions it doesn't know, it yields an `illegal hardware instruction` error.

**Comment by MikeMaxNow** [comment]
It is working for me!

**Comment by godly-devotion** [comment]
Awesome, thanks!
