### ISSUE TITLE
App still won't open 

### ISSUE THREAD

**Issue by Asada1** [godly-devotion/charge-limiter#35]
I did what you've said, but MacOs repeatedly told me to move it to the Bin. How open the app then?

**Comment by godly-devotion** [comment]
Have you tried moving the app to the Applications folder first? Also what version of macOS are you running?

**Comment by Asada1** [comment]
Thx, all works great! I forgot to text you back. Great app btw

Dziękuję, Amadeusz

**Comment by godly-devotion** [comment]
Good to hear! What was the issue?
