### ISSUE TITLE
Patreon page or buy me a coffee page?

### ISSUE THREAD

**Issue by cagnulein** [godly-devotion/charge-limiter#36]
Hi @godly-devotion i would really thank you for this project!
I have an old mac air 2013 that works really well and i would like to use it most of the time as a xcode server without destroying the battery. This project it's the main part of my project!

Don't you have a patreon page or a buy me a coffee page? I would like to thank you!

Thank you so much, and sorry to bother you with this!

**Comment by godly-devotion** [comment]
I’m happy to hear that. This app was only possible because of the work of others so I’m happy to just accept your gratitude.

**Comment by cagnulein** [comment]
@godly-devotion sponsored you :) enjoy the coffee!
