### ISSUE TITLE
Mac OS Ventura: Doesn't Work 

### ISSUE THREAD

**Issue by MikixIT** [godly-devotion/charge-limiter#43]
<img width="408" alt="Screenshot 2022-10-28 at 21 42 50" src="https://user-images.githubusercontent.com/66966279/198719471-c521c7d1-2b45-4479-8611-c636b9c0f520.png">
<img width="405" alt="Screenshot 2022-10-28 at 21 43 02" src="https://user-images.githubusercontent.com/66966279/198719492-1523cbeb-8ac1-498b-833e-15bb9cf9bb86.png">

After this setting (Yes, i put in application folder and use sudo) but still doesn't work

**Comment by geobio** [comment]
It might be because it doesn't work for m1 macs: https://github.com/godly-devotion/charge-limiter/issues/34

**Comment by MikixIT** [comment]
So, no support for M1 device?
