### ISSUE TITLE
What happens if you set a charge limit using this and enable Catalina's health management feature? 

### ISSUE THREAD

**Issue by sn0wyfall** [godly-devotion/charge-limiter#5]
Say I limited my charge to 50%, and used Catalina's health management feature. What would happen? Would it still charge/discharge? Or would that behavior stop?

**Comment by godly-devotion** [comment]
I am not running Catalina so I don't know. If I were to take a guess, the health management feature will probably not kick in if you limit your charge to 50% because it is no where near full charge since that feature is mainly there to not fully charge the battery until you need it.

**Comment by sn0wyfall** [comment]
thanks mate, mind if I wait for someone else to chime in to answer this question?

**Comment by sn0wyfall** [comment]
I went and enabled it while on the management feature. I set it to 80%. I'll notify y'all what happens when the battery next start going down. Currently at 100%. Wish me luck

**Comment by sn0wyfall** [comment]
Okay, so the battery level went down to 92% and is staying there. Usually it cycles between 100% and 89%. I'm going to give it another day and see what happens—will it decrease even more, or will it just stay there?

**Comment by sn0wyfall** [comment]
Okay, seems like it stops. Maybe the battery health management feature only works if you're actually charging to 100%.
